# Generated by Django 3.2.5 on 2021-07-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_course_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
