# Generated by Django 3.2.5 on 2021-07-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20210714_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
