# Generated by Django 3.2.5 on 2021-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_auto_20210714_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
