# Generated by Django 3.2.5 on 2021-07-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0006_institute_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
