# Generated by Django 3.2.4 on 2021-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0007_blog_blog_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
    ]
