# Generated by Django 3.2.5 on 2021-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0009_coursepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='date_time',
            new_name='enrollment_date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_sing',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_id',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
