# Generated by Django 3.2.5 on 2021-08-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0010_auto_20210806_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='amount',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price_enrollments', to='teaching.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
