# Generated by Django 3.2.4 on 2021-07-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0011_auto_20210701_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='uuid',
        ),
    ]
