# Generated by Django 3.2.5 on 2021-09-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0012_auto_20210826_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
