# Generated by Django 3.2.5 on 2021-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0014_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
