# Generated by Django 3.0.6 on 2020-10-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classappointed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.InstituteClass'),
        ),
    ]
