# Generated by Django 3.0.6 on 2020-10-01 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institute', '0002_auto_20201001_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='class_students', to='institute.InstituteClass'),
        ),
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute_students', to='institute.Institute'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instituteclass',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to='institute.Teacher'),
        ),
        migrations.AlterField(
            model_name='period',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='institute.Schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_schdule', to='institute.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject', to='institute.Teacher'),
        ),
    ]
