# Generated by Django 3.0.6 on 2020-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20201001_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
