# Generated by Django 3.1.2 on 2020-10-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_institute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
